import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { config as loadEnv } from "dotenv";
import { loadConfig } from "../config/loader.ts";
import { PipelineStateManager } from "./state.ts";
import { KieClient } from "../api/kie-client.ts";
import { generateVoiceovers } from "../api/tts.ts";
import { generateMusic } from "../api/music.ts";
import { generateVideoClips, interleaveClipsWithSlides } from "../api/video-gen.ts";
import { ExaClient, researchScenes, type ResearchResult } from "../api/research.ts";
import { loadEnhancedScripts, applyEnhancements } from "../api/enhance.ts";
import { mixAudio } from "../media/audio-mixer.ts";
import { composeVideo, useLocalVideo } from "../media/video-composer.ts";
import { logger } from "./logger.ts";
import { generateAllSlides, DEFAULT_SLIDE_STYLE } from "../media/slide-gen.ts";
import type { ProjectConfig, TTSResult, MusicResult, StepName, VideoClipInfo, SlideResult, SlideStyle } from "../types.ts";

export interface PipelineOptions {
  force?: boolean;
  dryRun?: boolean;
  steps?: StepName[];
}

export async function runPipeline(
  configPath: string,
  options: PipelineOptions = {}
): Promise<void> {
  // Load .env from pipeline directory and project root
  loadEnv({ path: resolve(dirname(configPath), "../.env") });
  loadEnv({ path: resolve(dirname(configPath), "../../.env") });
  loadEnv(); // Also check CWD

  // Load and validate config
  const config = loadConfig(configPath);
  const configContent = readFileSync(resolve(configPath), "utf-8");
  const outputDir = resolve(dirname(configPath), config.output.directory);

  // Resolve relative image paths in scenes to absolute paths (relative to config file)
  const configDir = dirname(resolve(configPath));
  for (const scene of config.scenes) {
    if (scene.image) scene.image = resolve(configDir, scene.image);
    if (scene.segments) {
      for (const seg of scene.segments) {
        if (seg.image) seg.image = resolve(configDir, seg.image);
      }
    }
  }

  logger.step("PIPELINE", `Project: ${config.project.name}`);
  logger.info(`  Slug: ${config.project.slug}`);
  logger.info(`  Scenes: ${config.scenes.length}`);
  logger.info(`  Output: ${outputDir}`);

  if (options.dryRun) {
    logger.info("\n  DRY RUN — config is valid, no actions taken.");
    printPlan(config);
    return;
  }

  const apiKey = process.env.KIE_API_KEY;
  if (!apiKey) {
    throw new Error(
      "KIE_API_KEY not found. Create a .env file with KIE_API_KEY=your_key"
    );
  }

  // Initialize state manager
  const state = new PipelineStateManager(outputDir, configContent, config.project.slug);

  if (options.force) {
    logger.warn("Force mode: resetting all steps");
    state.resetAll();
  }

  const client = new KieClient(apiKey);

  // ─── Step 0: Research (optional, uses Exa for deep research) ───
  const exaKey = process.env.EXA_API_KEY;
  let researchResults: ResearchResult[] = [];

  if (shouldRun("research", state, options) && exaKey) {
    state.markRunning("research");
    try {
      const exaClient = new ExaClient(exaKey);
      researchResults = await researchScenes(
        exaClient,
        config.scenes,
        config.project.description || config.project.name,
        outputDir
      );
      state.markCompleted("research", {
        files: Object.fromEntries(
          researchResults.map((r) => [r.sceneId, { file: r.query, duration_ms: 0 }])
        ),
      });
    } catch (err) {
      state.markFailed("research", (err as Error).message);
      logger.warn(`Research step failed (non-blocking): ${(err as Error).message}`);
      // Research is non-blocking — continue pipeline even if it fails
    }
  } else if (!exaKey && shouldRun("research", state, options)) {
    logger.info("  RESEARCH: skipped (no EXA_API_KEY)");
    state.markCompleted("research");
  } else if (state.isCompleted("research") && researchResults.length === 0) {
    // Research was cached — reload from disk
    const reportPath = join(outputDir, "research", "research-report.json");
    if (existsSync(reportPath)) {
      researchResults = JSON.parse(readFileSync(reportPath, "utf-8"));
      logger.info(`  RESEARCH: loaded ${researchResults.length} cached results from disk`);
    }
  }

  // ─── Step 0.5: Enhance scripts (pre-generated by Claude, loaded from cache) ───
  {
    const cached = loadEnhancedScripts(outputDir);
    if (cached) {
      applyEnhancements(config.scenes, cached);
      if (!state.isCompleted("enhance")) {
        state.markCompleted("enhance", {
          file: join(outputDir, "enhanced", "enhanced-scripts.json"),
        });
      }
      logger.info(`  ENHANCE: applied ${cached.length} enhanced scripts`);
    } else if (shouldRun("enhance", state, options)) {
      logger.info("  ENHANCE: no enhanced scripts found — using originals");
      logger.info("  (Run enhancement via Claude session to generate enhanced-scripts.json)");
      state.markCompleted("enhance");
    }
  }

  // ─── Step 1: TTS (voiceover generation) ───
  let ttsResults: TTSResult[] = [];

  if (shouldRun("tts", state, options)) {
    state.markRunning("tts");
    try {
      ttsResults = await generateVoiceovers(
        client,
        config.voice,
        config.scenes,
        outputDir
      );
      const files: Record<string, { file: string; duration_ms: number }> = {};
      for (const r of ttsResults) {
        files[r.sceneId] = { file: r.file, duration_ms: r.duration_ms };
      }
      state.markCompleted("tts", { files });
    } catch (err) {
      state.markFailed("tts", (err as Error).message);
      throw err;
    }
  } else if (state.isCompleted("tts")) {
    // Restore from state
    const outputs = state.get("tts").outputs;
    if (outputs?.files) {
      ttsResults = Object.entries(outputs.files).map(([sceneId, data]) => ({
        sceneId,
        file: data.file,
        duration_ms: data.duration_ms,
      }));
    }
    logger.info("  TTS: using cached results");
  }

  // Build duration map from TTS results
  const sceneDurations: Record<string, number> = {};
  for (const r of ttsResults) {
    sceneDurations[r.sceneId] = r.duration_ms + 500; // Add buffer
  }

  // Calculate total duration
  const totalDurationMs = ttsResults.reduce((sum, r) => sum + r.duration_ms, 0) +
    (ttsResults.length - 1) * (config.audio_mix.gap_between_scenes_seconds * 1000);

  // ─── Step 2: Music (parallel with TTS in future, sequential for now) ───
  let musicResult: MusicResult = { file: "", duration_ms: 0 };

  if (shouldRun("music", state, options)) {
    state.markRunning("music");
    try {
      musicResult = await generateMusic(
        client,
        config.music,
        totalDurationMs,
        outputDir
      );
      state.markCompleted("music", {
        file: musicResult.file,
        duration_ms: musicResult.duration_ms,
      });
    } catch (err) {
      state.markFailed("music", (err as Error).message);
      throw err;
    }
  } else if (state.isCompleted("music")) {
    const outputs = state.get("music").outputs;
    musicResult = {
      file: outputs?.file || "",
      duration_ms: outputs?.duration_ms || 0,
    };
    logger.info("  MUSIC: using cached results");
  }

  // ─── Step 3: Video generation ───
  let videoFile = "";
  let videoClips: VideoClipInfo[] = [];

  if (shouldRun("video", state, options)) {
    state.markRunning("video");
    try {
      if (config.visual.source === "local-file" && config.visual.local_file) {
        const result = await useLocalVideo(config.visual.local_file, outputDir);
        videoFile = result.file;
        state.markCompleted("video", {
          file: result.file,
          duration_ms: result.duration_ms,
        });
      } else if (
        config.visual.source === "image-to-video" ||
        config.visual.source === "ai-generate"
      ) {
        const result = await generateVideoClips(
          client,
          config.visual,
          config.scenes,
          sceneDurations,
          outputDir
        );
        videoFile = result.file;
        videoClips = result.clips || [];
        state.markCompleted("video", {
          file: result.file,
          duration_ms: result.duration_ms,
          clips: result.clips,
        });
      } else if (config.visual.source === "react-capture") {
        const { captureReactVideo } = await import("../api/react-capture.ts");
        const projectRoot = resolve(dirname(configPath), "..");
        const result = await captureReactVideo(
          config.visual,
          config.scenes,
          outputDir,
          projectRoot
        );
        videoFile = result.file;
        state.markCompleted("video", {
          file: result.file,
          duration_ms: result.duration_ms,
        });
      } else {
        throw new Error(
          `Unknown visual source: ${config.visual.source}. ` +
          `Supported: image-to-video, ai-generate, local-file, react-capture`
        );
      }
    } catch (err) {
      state.markFailed("video", (err as Error).message);
      throw err;
    }
  } else if (state.isCompleted("video")) {
    videoFile = state.get("video").outputs?.file || "";
    videoClips = (state.get("video").outputs?.clips as VideoClipInfo[]) || [];
    logger.info("  VIDEO: using cached results");
  }

  // ─── Step 3.5: Generate slides (interleave with video clips) ───
  let slideResults: SlideResult[] = [];

  if (shouldRun("slides", state, options)) {
    if (config.slides?.enabled && videoClips.length > 0 && ttsResults.length > 0) {
      state.markRunning("slides");
      try {
        const slideStyle = { ...DEFAULT_SLIDE_STYLE, ...config.slides.style } as Required<SlideStyle>;
        slideResults = await generateAllSlides(
          config.scenes,
          ttsResults,
          videoClips,
          config.audio_mix.gap_between_scenes_seconds,
          slideStyle,
          outputDir
        );

        // Interleave slides with Veo clips → new combined.mp4
        if (slideResults.length > 0) {
          const combined = await interleaveClipsWithSlides(videoClips, slideResults, outputDir);
          videoFile = combined.file;
          state.markCompleted("slides", {
            file: combined.file,
            duration_ms: combined.duration_ms,
            clips: combined.clips,
          });
          logger.step("SLIDES", `Interleaved ${slideResults.length} slides → ${Math.round(combined.duration_ms / 1000)}s video`);
        } else {
          state.markCompleted("slides");
          logger.info("  SLIDES: no slides needed (all scenes filled by Veo clips)");
        }
      } catch (err) {
        state.markFailed("slides", (err as Error).message);
        throw err;
      }
    } else {
      logger.info("  SLIDES: disabled or missing data");
      state.markCompleted("slides");
    }
  } else if (state.isCompleted("slides")) {
    const slidesOutput = state.get("slides").outputs;
    if (slidesOutput?.file) {
      videoFile = slidesOutput.file;
    }
    logger.info("  SLIDES: using cached results");
  }

  // ─── Step 4: Audio mixing ───
  let mixedAudioFile = "";

  if (shouldRun("mix_audio", state, options)) {
    state.markRunning("mix_audio");
    try {
      if (ttsResults.length === 0) throw new Error("No TTS results to mix");
      if (!musicResult.file) throw new Error("No music file to mix");

      const result = await mixAudio(ttsResults, musicResult, config.audio_mix, outputDir);
      mixedAudioFile = result.file;
      state.markCompleted("mix_audio", {
        file: result.file,
        duration_ms: result.duration_ms,
      });
    } catch (err) {
      state.markFailed("mix_audio", (err as Error).message);
      throw err;
    }
  } else if (state.isCompleted("mix_audio")) {
    mixedAudioFile = state.get("mix_audio").outputs?.file || "";
    logger.info("  MIX: using cached results");
  }

  // ─── Step 5: Final composition ───
  if (shouldRun("compose", state, options)) {
    state.markRunning("compose");
    try {
      if (!videoFile) throw new Error("No video file for composition");
      if (!mixedAudioFile) throw new Error("No mixed audio file for composition");

      const result = await composeVideo(
        videoFile,
        mixedAudioFile,
        config.output,
        config.project.slug
      );

      state.markCompleted("compose", {
        file: result.file,
        duration_ms: result.duration_ms,
      });

      logger.step("DONE", `Video ready: ${result.file}`);
      logger.info(`  Duration: ${(result.duration_ms / 1000).toFixed(1)}s`);
      logger.info(`  Size: ${result.file_size_mb} MB`);
    } catch (err) {
      state.markFailed("compose", (err as Error).message);
      throw err;
    }
  } else if (state.isCompleted("compose")) {
    logger.step("DONE", "Video already composed (cached)");
  }
}

function shouldRun(
  step: StepName,
  state: PipelineStateManager,
  options: PipelineOptions
): boolean {
  if (options.steps && !options.steps.includes(step)) return false;
  if (options.force) return true;
  return !state.isCompleted(step);
}

function printPlan(config: ProjectConfig): void {
  const hasExa = !!process.env.EXA_API_KEY;
  console.log("\n  Pipeline Plan:");
  console.log(`  0. RESEARCH: ${hasExa ? "Exa deep search (enabled)" : "skipped (no EXA_API_KEY)"}`);
  console.log(`  0.5 ENHANCE: ${hasExa ? "LLM script enhancement with research context" : "skipped (needs research)"}`);
  console.log(`  1. TTS: ${countScripts(config)} voiceover clips via ${config.voice.provider}`);
  console.log(`  2. MUSIC: ${config.music.provider} (${config.music.mode || "instrumental"})`);
  console.log(`  3. VIDEO: ${config.visual.source}`);
  console.log(`  3.5 SLIDES: ${config.slides?.enabled ? "enabled" : "disabled"}`);
  console.log(`  4. MIX: voiceover @ ${config.audio_mix.voiceover_volume_db}dB + music @ ${config.audio_mix.music_volume_db}dB`);
  console.log(`  5. COMPOSE: ${config.output.resolution.width}x${config.output.resolution.height} @ ${config.output.fps}fps`);
}

function countScripts(config: ProjectConfig): number {
  let count = 0;
  for (const s of config.scenes) {
    if (s.segments) count += s.segments.length;
    else if (s.script) count += 1;
  }
  return count;
}

export async function showStatus(configPath: string): Promise<void> {
  const config = loadConfig(configPath);
  const configContent = readFileSync(resolve(configPath), "utf-8");
  const outputDir = resolve(dirname(configPath), config.output.directory);

  const state = new PipelineStateManager(outputDir, configContent, config.project.slug);
  const all = state.getAll();

  console.log(`\nPipeline Status: ${config.project.name}`);
  console.log(`Config hash: ${all.config_hash}`);
  console.log(`Started: ${all.started_at}\n`);

  const ICONS: Record<string, string> = {
    pending: "  ",
    running: ">>",
    completed: "OK",
    failed: "!!",
  };

  for (const [step, s] of Object.entries(all.steps)) {
    const icon = ICONS[s.status] || "??";
    let line = `  [${icon}] ${step.padEnd(12)} ${s.status}`;
    if (s.completed_at) line += ` (${s.completed_at})`;
    if (s.error) line += ` — ${s.error}`;
    console.log(line);
  }
}
